volumes:
  postgres-data:
  valkey-data:

services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: postgres.internal
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.1.3-bookworm
    container_name: valkey.internal
    restart: always
    ports:
      - "6379:6379"
    environment:
      VALKEY_EXTRA_FLAGS: --save 60 1 --loglevel warning
    volumes:
      - valkey-data:/data
